### PR TITLE
Cmsc495 17

### PR DESCRIPTION
**Pull request by cotey-gh**

### CODE REVIEW

**Comment by ConnorDBurge** [comment]
@cotey-gh, I pulled these changes down and found an issue. You can login and save the accessToken to local storage fine. But the user state in the AuthenticationProvider never updates. It just stays null. This is due to the `useEffect` running only when the component mounts. It does not re render when local storage is updated. So, I added a sign in method to the AuthenticationProvider. It will be used from the `useAuth` hook you made. It just passes the creds off to the AuthService method. We'll do our sign up and sign out methods this was as well. I pushed these changes up for you.

```javascript
export const AuthenticationProvider = ({ children }) => {
  const [user, setUser] = useState(null);

  const signIn = async (credentials) => {
    const data = await authService.signIn(credentials);

    if (data?.accessToken) {
      const { sub, email, userId } = jwt_decode(data.accessToken);
      setUser({ sub, email, userId });
    }
  };

  // This useEffect will run only once, when the component mounts
  useEffect(() => {
    const token = localStorage.getItem("accessToken");
    if (token) {
      const { sub, email, userId } = jwt_decode(token);
      setUser({ sub, email, userId });
    }
  }, []);

  return (
    <AuthContext.Provider value={{ user, setUser, signIn }}>
      {children}
    </AuthContext.Provider>
  );
};
 ```

**Review by ConnorDBurge — APPROVED** [review]

**Comment by ConnorDBurge** [comment]
Another thing to point out, I have Heroku configured to post a review app to test out. It deploys a new instance of the app with this branch. You can click the `View Deployment` button up above. But I need to re configure the CORS policy on the backend. Its only allowing local host and the testing environment app in Heroku. I'll probably just set it to allow all `*`.

**Comment by cotey-gh** [comment]
@ConnorDBurge thanks. I meant to mention when I did the last push that I was not sure it was decoding the accessToken correctly because I was not seeing the user info (e.g., name, id, etc.) broken out in the browser. I was a bit confused though because it was working for us yesterday, and I did not change anything in AuthenticationProvider today -- just added the ServicesProvider. I thought maybe wrapping the app in the SP caused decoding issues.

**Comment by cotey-gh** [comment]
@ConnorDBurge one question. Do we want to use `credentials` or `body` there in the new `signIn` method? We use `body` in the `AuthService` class, so wanted to make sure.

**Comment by cotey-gh** [comment]
> Another thing to point out, I have Heroku configured to post a review app to test out. It deploys a new instance of the app with this branch. You can click the `View Deployment` button up above. But I need to re configure the CORS policy on the backend. Its only allowing local host and the testing environment app in Heroku. I'll probably just set it to allow all `*`.

Yeah, I get a CORS error there right now.

**Comment by ConnorDBurge** [comment]
> > Another thing to point out, I have Heroku configured to post a review app to test out. It deploys a new instance of the app with this branch. You can click the `View Deployment` button up above. But I need to re configure the CORS policy on the backend. Its only allowing local host and the testing environment app in Heroku. I'll probably just set it to allow all `*`.
> 
> Yeah, I get a CORS error there right now.

Yeah, the app works great. Just getting block on the HTTP request.

**Pull request merged**
